### ISSUE TITLE
Как добавить слайсер?

### ISSUE THREAD

**Issue by Renatfg** [vassav/KISSlicerPlugin#1]
Подскажите, никак не разберусь! :)

Как добавить слайсер? В списке Менеджера он не появляется у меня!

Спасибо.

**Comment by vassav** [comment]
Добрый день. Я немного не корректно сделал описание:
1.Содержимое архива распаковать в папку [Repetier-Host]\plugins\KISSlicerPlugin
После этого запустить (или перезапустить) RepeaterHost.
На вкладке Slicer в списке появится "KISSlicer", а дальше уже по списку

**Comment by Renatfg** [comment]
Я перезапускал уже неоднократно :) И пути проверял. Никак!
Возможно как-то связано с правами на папку? (система Windows 10)

**Comment by vassav** [comment]
Папка с плагином (см. путь):
![folder](https://cloud.githubusercontent.com/assets/1650765/15749265/6b941a7c-28ea-11e6-92e3-a05056e89a2a.png)
Настройка слайсера:
![slicermanager](https://cloud.githubusercontent.com/assets/1650765/15749275/74bc9cc8-28ea-11e6-8cda-dcae2a855ac1.png)
Вкладка со слайсером:
![mainpage](https://cloud.githubusercontent.com/assets/1650765/15749282/7b462a5a-28ea-11e6-80fa-2332cd29a61b.png)

**Comment by Renatfg** [comment]
Вот и не понятно, все проверил! Даже на вхождение русских букв в путь.
![2016-06-03_12-04-09](https://cloud.githubusercontent.com/assets/5832157/15774147/876c90f0-2983-11e6-89d8-7b295ab0df42.png)

**Comment by Renatfg** [comment]
Возможно это связано с версией репитера, у Вас 1.5.6 у меня 1.6.1
Как думаете?

**Comment by vassav** [comment]
А что выводит RepeaterHost в логи?
Может файл заблокирован. Тогда проверьте:
![fileproperty](https://cloud.githubusercontent.com/assets/1650765/15777556/f812152c-2998-11e6-805e-9c4b1d6c3502.png)

**Comment by Renatfg** [comment]
Вот это помогло! Но теперь есть новое затруднение - кисс при запуске не находит передаваемый файл, при этом файл на диске есть и он хороший. Выдает последовательно такие сообщения:

![2016-06-03_17-35-36](https://cloud.githubusercontent.com/assets/5832157/15782146/c3fccfb6-29b1-11e6-976e-01f9b3b75f3a.png)

![2016-06-03_17-36-04](https://cloud.githubusercontent.com/assets/5832157/15782155/d0365612-29b1-11e6-9c3c-cb2c1edfccb4.png)

![2016-06-03_17-36-28](https://cloud.githubusercontent.com/assets/5832157/15782159/d622f4f4-29b1-11e6-8d1c-c0701938962c.png)

Настройки плагина:

![2016-06-03_17-39-43](https://cloud.githubusercontent.com/assets/5832157/15782241/32d2e254-29b2-11e6-9b34-f17fe4eb3ced.png)

Файл:

![2016-06-03_17-42-51](https://cloud.githubusercontent.com/assets/5832157/15782371/ad15a402-29b2-11e6-97b6-8baec91775de.png)

И еще, не уверен связанно ли это но выходной путь C:\Program Files (x86)\Magnum3D\composition.gcode не используется при сохранении, предлагает сохранять в текущую папку.

**Comment by Renatfg** [comment]
Кстати где логи у репитера не нашел :(

**Comment by vassav** [comment]
Отображение логов:
![log](https://cloud.githubusercontent.com/assets/1650765/15783700/e0ff2162-29b7-11e6-9335-1af8c0ed65ab.png)

Так же проверьте настройки рабочей папки RepeaterHost:
![worckdir](https://cloud.githubusercontent.com/assets/1650765/15783736/116af93e-29b8-11e6-989c-47bc618d0fc0.png)
Это не должна быть папка для которой требуются повышенные привилегии и не нодержать пробелов.
В эту папку репитер сохраняет временный скомпонованный файл, который потом и открывается в KISSlicer.

По поводу пробелов в рабочей папке - это бага, нужно будет поправить

**Comment by Renatfg** [comment]
Да действительно как только сделал рабочую папку Репитера без пробелов, то он стал открывать файл. А у меня рабочаяя папка в C:\Program Files (x86)\ и собственно тут есть проблемы :)
Пофиксите будет отлично! :)

И еще подскажите, после закрытия киса, репитер не открывает отслайсенный файл. Так должно быть или он должен его схватывать?

**Comment by vassav** [comment]
В кисе нужно отслайсить файл и сохранить gcod по пути как в настройках плагина (Output gcode file).
Плагин отслеживает изменение этого файла, и как только он обновится подгружает его в репитер

**Comment by Renatfg** [comment]
Проверил это работает тоже только если рабочая папка без пробелов.

Еще обнаружил некоторый трабл - при работе с двумя экструдерами репитер сохраняет два файла - composition0.stl и composition1.stl - их надо оба загрузить в кисс. Сейчас загружается только composition0.stl

**Comment by Renatfg** [comment]
И если есть возможность присвоить сразу файлы разным экструдерам.

**Comment by vassav** [comment]
На счет двух файлов - спасибо, тоже поправлю.
По поводу привязки к экструдеру - тут все печальнее. Я смог только загружать модели в кисс, и больше не знаю как с ним работать. Писал на официальном форуме - то никто не ответил.
[http://www.kisslicertalk.com/viewtopic.php?f=11&t=1301](url)
Буду рад любой помощи в этом плане.

**Comment by Renatfg** [comment]
Вот я кое что нашел на эту тему: 
https://groups.google.com/forum/#!topicsearchin/kisslicer-refugee-camp/subject$3Acommand/kisslicer-refugee-camp/CL83yoDD1Ww

Но как присвоить файл экструдеру непонятно.

**Comment by vassav** [comment]
Поправил баг с пробелами.
В кис теперь передаются все файлы из репитера разбитые по экструдерам.
[Новая версия](https://github.com/vassav/KISSlicerPlugin/blob/master/Bins/KISSlicerPlugin.1.0.1.zip)

Спасибо за ссылку, опция с автоматической генерацией файла работает. Добавлю это в ближайшее время.

**Comment by vassav** [comment]
Добавил возможность автоматического слайсинга из репитера с использованием последних настроек KISSlicer.

**Comment by Renatfg** [comment]
Не присваиваются экструдеру. Какую команду используете?
И не запускается автоматический слайсинг, если я правильно понял идею.
Также если нажать кнопку сохранить то предлагается сохранить файл composition0.gcode
(А при 2-х экструдерах composition0.gcode composition1.gcode)

А нужен файл composition.gcode

**Comment by Renatfg** [comment]
.. НЕ запускается автоматический слайсинг .. :)

**Comment by Renatfg** [comment]
И кстати, перестал подгружаться автоматом файл composition.gcode
Это может быть связано с тем что я обратно вернул все в папку с пробелами в имени.

**Comment by vassav** [comment]
С авто слайсингом была бага. (поправил)
[v 1.0.2.1](https://github.com/vassav/KISSlicerPlugin/blob/master/Bins/KISSlicerPlugin.1.0.2.1.zip).

По поводу привязки экструдеров - пока не понятки. Как вариант можно так:
Назначаем модели разным экструдерам:
![f1](https://cloud.githubusercontent.com/assets/1650765/15830531/8cab416a-2c21-11e6-8e88-9c0dd5d457b3.png)
Запускаем кис и открываем "Extruder mappind":
![extruder_map](https://cloud.githubusercontent.com/assets/1650765/15834497/749626fe-2c34-11e6-9459-9e0015bd9ed0.png)
назначаем:
composition0.stl -> ext.1
composition1.stl -> ext.2
У меня нет PRO версии поэтому проверить не могу.
Слайсим и сохраняем (если сохранить по пути как в настройках слайсера, то он подгрузится в репитере, если имя или путь не совпадает - не загрузится).

**Comment by vassav** [comment]
> И кстати, перестал подгружаться автоматом файл composition.gcode
> Это может быть связано с тем что я обратно вернул все в папку с пробелами
> в имени.
> Скорее всего сохраняешь под другим именем файл (не как в настройках)
